# Generated by Django 4.1.3 on 2022-12-03 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-update", "-created"]},
        ),
        migrations.AddField(
            model_name="room",
            name="participtants",
            field=models.ManyToManyField(
                blank=True, related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
