# Generated by Django 4.1.3 on 2022-12-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_room_options_room_participtants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="participtants",
            new_name="members",
        ),
    ]
